Geojson to csv conversion test
weecology/retriever pull request #1504
Opened 2020-07-29 01:32 UTC by ashishpriyadarshiCIC

For testing the function added in #1485 . A [script](https://github.com/weecology/retriever-recipes/pull/74) is added in retriever-recipies for using this testing function

2020-07-29 01:36 UTC, ashishpriyadarshiCIC commented
To test this use the command `retriever install csv lake-county-illinois-cancer-rates` and here is the output

![image](https://user-images.githubusercontent.com/31954786/88746340-f32ff880-d169-11ea-9d1a-dd8199f531f2.png)

2020-08-24 14:15 UTC, apoorvaeternity requested changes
Couple of comments but looks good.

2020-08-24 14:15 UTC, apoorvaeternity commented on retriever/lib/engine_tools.py
> +except:
`except ModuleNotFoundError`

2020-08-24 16:57 UTC, ashishpriyadarshiCIC commented on test/test_retriever.py
> +try:
The tests on Travis and Appveyor are showing issues in installing geopandas library.

2020-08-24 20:34 UTC, ashishpriyadarshiCIC commented on test/test_regression.py
> +# def test_fetch():
The datasets were not online when this PR was made initially, It's online now so I will uncomment it

2020-08-25 16:19 UTC, ashishpriyadarshiCIC commented
@apoorvaeternity @henrykironde Ready for review

2020-08-26 05:04 UTC, henrykironde commented on .travis.yml
> +  - docker-compose run --service-ports python_retriever pytest -v -k "not test_geojson2csv" --cov=retriever
Adding a comment here would be nice and also in the try blocks 

```
try:
     # Geopanda installation is not smooth on the CI tests platforms
     import geopandas
 except ModuleNotFoundError:
     pass
```

2020-08-29 12:12 UTC, apoorvaeternity approved these changes
LGTM!!!

2020-09-01 04:50 UTC, henrykironde commented
Check out the comments and update each of them. Looks good but need to take care of the commetns

2020-09-01 19:26 UTC, merged